defaults: &defaults
  host: localhost
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  sessions:
    default:
      database: shelr-dev
      hosts:
        - localhost:27017


test:
  sessions:
    default:
      database: shelr-test
      hosts:
        - localhost:27017

# set these environment variables on your prod server
production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
      #host: <%= ENV['MONGOID_HOST'] %>
      #port: <%= ENV['MONGOID_PORT'] %>
      #username: <%= ENV['MONGOID_USERNAME'] %>
      #password: <%= ENV['MONGOID_PASSWORD'] %>
      #database: <%= ENV['MONGOID_DATABASE'] %>
